// Generated by gencpp from file control/PickUpBallResponse.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_PICKUPBALLRESPONSE_H
#define CONTROL_MESSAGE_PICKUPBALLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control
{
template <class ContainerAllocator>
struct PickUpBallResponse_
{
  typedef PickUpBallResponse_<ContainerAllocator> Type;

  PickUpBallResponse_()
    : ok(false)  {
    }
  PickUpBallResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::control::PickUpBallResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::PickUpBallResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickUpBallResponse_

typedef ::control::PickUpBallResponse_<std::allocator<void> > PickUpBallResponse;

typedef boost::shared_ptr< ::control::PickUpBallResponse > PickUpBallResponsePtr;
typedef boost::shared_ptr< ::control::PickUpBallResponse const> PickUpBallResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::PickUpBallResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::PickUpBallResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::PickUpBallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::PickUpBallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::PickUpBallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::PickUpBallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::PickUpBallResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::PickUpBallResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::PickUpBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::control::PickUpBallResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::PickUpBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/PickUpBallResponse";
  }

  static const char* value(const ::control::PickUpBallResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::PickUpBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool ok\n\
\n\
";
  }

  static const char* value(const ::control::PickUpBallResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::PickUpBallResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickUpBallResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::PickUpBallResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::PickUpBallResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_PICKUPBALLRESPONSE_H
