// Generated by gencpp from file control/PickUpBall.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_PICKUPBALL_H
#define CONTROL_MESSAGE_PICKUPBALL_H

#include <ros/service_traits.h>


#include <control/PickUpBallRequest.h>
#include <control/PickUpBallResponse.h>


namespace control
{

struct PickUpBall
{

typedef PickUpBallRequest Request;
typedef PickUpBallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickUpBall
} // namespace control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control::PickUpBall > {
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::control::PickUpBall&) { return value(); }
};

template<>
struct DataType< ::control::PickUpBall > {
  static const char* value()
  {
    return "control/PickUpBall";
  }

  static const char* value(const ::control::PickUpBall&) { return value(); }
};


// service_traits::MD5Sum< ::control::PickUpBallRequest> should match 
// service_traits::MD5Sum< ::control::PickUpBall > 
template<>
struct MD5Sum< ::control::PickUpBallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control::PickUpBall >::value();
  }
  static const char* value(const ::control::PickUpBallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control::PickUpBallRequest> should match 
// service_traits::DataType< ::control::PickUpBall > 
template<>
struct DataType< ::control::PickUpBallRequest>
{
  static const char* value()
  {
    return DataType< ::control::PickUpBall >::value();
  }
  static const char* value(const ::control::PickUpBallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control::PickUpBallResponse> should match 
// service_traits::MD5Sum< ::control::PickUpBall > 
template<>
struct MD5Sum< ::control::PickUpBallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control::PickUpBall >::value();
  }
  static const char* value(const ::control::PickUpBallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control::PickUpBallResponse> should match 
// service_traits::DataType< ::control::PickUpBall > 
template<>
struct DataType< ::control::PickUpBallResponse>
{
  static const char* value()
  {
    return DataType< ::control::PickUpBall >::value();
  }
  static const char* value(const ::control::PickUpBallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_MESSAGE_PICKUPBALL_H
