// Generated by gencpp from file control/ThrowBallRequest.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_THROWBALLREQUEST_H
#define CONTROL_MESSAGE_THROWBALLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control
{
template <class ContainerAllocator>
struct ThrowBallRequest_
{
  typedef ThrowBallRequest_<ContainerAllocator> Type;

  ThrowBallRequest_()
    : pixel_height(0.0)  {
    }
  ThrowBallRequest_(const ContainerAllocator& _alloc)
    : pixel_height(0.0)  {
  (void)_alloc;
    }



   typedef double _pixel_height_type;
  _pixel_height_type pixel_height;





  typedef boost::shared_ptr< ::control::ThrowBallRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::ThrowBallRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ThrowBallRequest_

typedef ::control::ThrowBallRequest_<std::allocator<void> > ThrowBallRequest;

typedef boost::shared_ptr< ::control::ThrowBallRequest > ThrowBallRequestPtr;
typedef boost::shared_ptr< ::control::ThrowBallRequest const> ThrowBallRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::ThrowBallRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::ThrowBallRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::ThrowBallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::ThrowBallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::ThrowBallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::ThrowBallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::ThrowBallRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::ThrowBallRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::ThrowBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52954f9f105493b6185412c8ca3e9ab4";
  }

  static const char* value(const ::control::ThrowBallRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52954f9f105493b6ULL;
  static const uint64_t static_value2 = 0x185412c8ca3e9ab4ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::ThrowBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/ThrowBallRequest";
  }

  static const char* value(const ::control::ThrowBallRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::ThrowBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 pixel_height\n\
";
  }

  static const char* value(const ::control::ThrowBallRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::ThrowBallRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pixel_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrowBallRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::ThrowBallRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::ThrowBallRequest_<ContainerAllocator>& v)
  {
    s << indent << "pixel_height: ";
    Printer<double>::stream(s, indent + "  ", v.pixel_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_THROWBALLREQUEST_H
