(cl:defpackage computer_vision-srv
  (:use )
  (:export
   "GETBALLPOSE"
   "<GETBALLPOSE-REQUEST>"
   "GETBALLPOSE-REQUEST"
   "<GETBALLPOSE-RESPONSE>"
   "GETBALLPOSE-RESPONSE"
   "GETTARGETPOSE"
   "<GETTARGETPOSE-REQUEST>"
   "GETTARGETPOSE-REQUEST"
   "<GETTARGETPOSE-RESPONSE>"
   "GETTARGETPOSE-RESPONSE"
  ))

