// Generated by gencpp from file computer_vision/GetBallPoseResponse.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_GETBALLPOSERESPONSE_H
#define COMPUTER_VISION_MESSAGE_GETBALLPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace computer_vision
{
template <class ContainerAllocator>
struct GetBallPoseResponse_
{
  typedef GetBallPoseResponse_<ContainerAllocator> Type;

  GetBallPoseResponse_()
    : ball_pose()  {
    }
  GetBallPoseResponse_(const ContainerAllocator& _alloc)
    : ball_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _ball_pose_type;
  _ball_pose_type ball_pose;





  typedef boost::shared_ptr< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetBallPoseResponse_

typedef ::computer_vision::GetBallPoseResponse_<std::allocator<void> > GetBallPoseResponse;

typedef boost::shared_ptr< ::computer_vision::GetBallPoseResponse > GetBallPoseResponsePtr;
typedef boost::shared_ptr< ::computer_vision::GetBallPoseResponse const> GetBallPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::GetBallPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace computer_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d7a58f8ac7c61cd568e699d96ad3e1c";
  }

  static const char* value(const ::computer_vision::GetBallPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d7a58f8ac7c61cdULL;
  static const uint64_t static_value2 = 0x568e699d96ad3e1cULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/GetBallPoseResponse";
  }

  static const char* value(const ::computer_vision::GetBallPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/PoseStamped ball_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::computer_vision::GetBallPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ball_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBallPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::GetBallPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_vision::GetBallPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "ball_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ball_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_GETBALLPOSERESPONSE_H
