// Generated by gencpp from file computer_vision/GetBallPoseRequest.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_GETBALLPOSEREQUEST_H
#define COMPUTER_VISION_MESSAGE_GETBALLPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace computer_vision
{
template <class ContainerAllocator>
struct GetBallPoseRequest_
{
  typedef GetBallPoseRequest_<ContainerAllocator> Type;

  GetBallPoseRequest_()
    {
    }
  GetBallPoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBallPoseRequest_

typedef ::computer_vision::GetBallPoseRequest_<std::allocator<void> > GetBallPoseRequest;

typedef boost::shared_ptr< ::computer_vision::GetBallPoseRequest > GetBallPoseRequestPtr;
typedef boost::shared_ptr< ::computer_vision::GetBallPoseRequest const> GetBallPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::GetBallPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace computer_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::computer_vision::GetBallPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/GetBallPoseRequest";
  }

  static const char* value(const ::computer_vision::GetBallPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::computer_vision::GetBallPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBallPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::GetBallPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::computer_vision::GetBallPoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_GETBALLPOSEREQUEST_H
