// Generated by gencpp from file computer_vision/GetTargetPose.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_GETTARGETPOSE_H
#define COMPUTER_VISION_MESSAGE_GETTARGETPOSE_H

#include <ros/service_traits.h>


#include <computer_vision/GetTargetPoseRequest.h>
#include <computer_vision/GetTargetPoseResponse.h>


namespace computer_vision
{

struct GetTargetPose
{

typedef GetTargetPoseRequest Request;
typedef GetTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTargetPose
} // namespace computer_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::computer_vision::GetTargetPose > {
  static const char* value()
  {
    return "1d7a58f8ac7c61cd568e699d96ad3e1c";
  }

  static const char* value(const ::computer_vision::GetTargetPose&) { return value(); }
};

template<>
struct DataType< ::computer_vision::GetTargetPose > {
  static const char* value()
  {
    return "computer_vision/GetTargetPose";
  }

  static const char* value(const ::computer_vision::GetTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::computer_vision::GetTargetPoseRequest> should match 
// service_traits::MD5Sum< ::computer_vision::GetTargetPose > 
template<>
struct MD5Sum< ::computer_vision::GetTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::computer_vision::GetTargetPose >::value();
  }
  static const char* value(const ::computer_vision::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::computer_vision::GetTargetPoseRequest> should match 
// service_traits::DataType< ::computer_vision::GetTargetPose > 
template<>
struct DataType< ::computer_vision::GetTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::computer_vision::GetTargetPose >::value();
  }
  static const char* value(const ::computer_vision::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::computer_vision::GetTargetPoseResponse> should match 
// service_traits::MD5Sum< ::computer_vision::GetTargetPose > 
template<>
struct MD5Sum< ::computer_vision::GetTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::computer_vision::GetTargetPose >::value();
  }
  static const char* value(const ::computer_vision::GetTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::computer_vision::GetTargetPoseResponse> should match 
// service_traits::DataType< ::computer_vision::GetTargetPose > 
template<>
struct DataType< ::computer_vision::GetTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::computer_vision::GetTargetPose >::value();
  }
  static const char* value(const ::computer_vision::GetTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_GETTARGETPOSE_H
