(cl:defpackage control-srv
  (:use )
  (:export
   "PICKUPBALL"
   "<PICKUPBALL-REQUEST>"
   "PICKUPBALL-REQUEST"
   "<PICKUPBALL-RESPONSE>"
   "PICKUPBALL-RESPONSE"
   "THROWBALL"
   "<THROWBALL-REQUEST>"
   "THROWBALL-REQUEST"
   "<THROWBALL-RESPONSE>"
   "THROWBALL-RESPONSE"
  ))

